### ISSUE TITLE
Spawn ENOENT Issue

### ISSUE THREAD

**Issue by mxfeinberg** [chasemc/electricShine#109]
Hello @chasemc ,

I'm sorry to bother you again, but I just ran into a different issue when attempting to run the executables on other computers.  I get the following error: 

![image](https://user-images.githubusercontent.com/7530298/65193356-aa7abf80-da2f-11e9-8ae5-4b3b5f3feb94.png)

I think it may be linked to [this](https://github.com/chasemc/electricShine/blob/a2c5dfb67a5fb79234aa51461377c36029ff7669/inst/template/src/background.js#L56) where the path isn't properly parameterized?  I'm looking into it now but if you have any insights that would be appreciated.

I really appreciate your help!

**Comment by chasemc** [comment]
Its the same problem with the paths, solved with shquote. I'll push the fix tonight or tomorrow

**Comment by mxfeinberg** [comment]
Okay! I will be on the lookout for that commit. Thanks again

**Comment by mxfeinberg** [comment]
Hey Chase,  thanks for submitting that commit.  Unfortunately, it did not resolve that issue I was facing which seems to be with [this](https://github.com/chasemc/electricShine/blob/1ef93242ff98b0de6dfef594ee261161c09fedad/inst/template/src/background.js#L34) line.

I fixed it with this `var rresources = (app.getAppPath().concat("\\app\\r_lang")).replace(/\\/g, "/");`

**Comment by chasemc** [comment]
Should all be fixed.  Changes have been merged into master branch.
There's still at least one issue that needs to be addressed before this is ready to be used:
https://github.com/chasemc/electricShine/issues/128 will try to get to that this week
